apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  namespace: otel-demo
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: 2.0.2
    app.kubernetes.io/part-of: opentelemetry-demo
data:
  demo.flagd.json: "{\n  \"$schema\": \"https://flagd.dev/schema/v0/flags.json\",\n\
    \  \"flags\": {\n    \"productCatalogFailure\": {\n      \"description\": \"Fail\
    \ product catalog service on a specific product\",\n      \"state\": \"ENABLED\"\
    ,\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n    \
    \  },\n      \"defaultVariant\": \"off\"\n    },\n    \"recommendationCacheFailure\"\
    : {\n      \"description\": \"Fail recommendation service cache\",\n      \"state\"\
    : \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\"\
    : false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"adManualGc\"\
    : {\n      \"description\": \"Triggers full manual garbage collections in the\
    \ ad service\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n      \
    \  \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\":\
    \ \"off\"\n    },\n    \"adHighCpu\": {\n      \"description\": \"Triggers high\
    \ cpu load in the ad service\",\n      \"state\": \"ENABLED\",\n      \"variants\"\
    : {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\"\
    : \"off\"\n    },\n    \"adFailure\": {\n      \"description\": \"Fail ad service\"\
    ,\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n\
    \        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n\
    \    \"kafkaQueueProblems\": {\n      \"description\": \"Overloads Kafka queue\
    \ while simultaneously introducing a consumer side delay leading to a lag spike\"\
    ,\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": 100,\n\
    \        \"off\": 0\n      },\n      \"defaultVariant\": \"off\"\n    },\n   \
    \ \"cartFailure\": {\n      \"description\": \"Fail cart service\",\n      \"\
    state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"\
    off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"paymentFailure\"\
    : {\n      \"description\": \"Fail payment service charge requests n%\",\n   \
    \   \"state\": \"ENABLED\",\n      \"variants\": {\n        \"100%\": 1,\n   \
    \     \"90%\": 0.95,\n        \"75%\": 0.75,\n        \"50%\": 0.5,\n        \"\
    25%\": 0.25,\n        \"10%\": 0.1,\n        \"off\": 0\n      },\n      \"defaultVariant\"\
    : \"off\"\n    },\n    \"paymentUnreachable\": {\n      \"description\": \"Payment\
    \ service is unavailable\",\n      \"state\": \"ENABLED\",\n      \"variants\"\
    : {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\"\
    : \"off\"\n    },\n    \"loadGeneratorFloodHomepage\": {\n      \"description\"\
    : \"Flood the frontend with a large amount of requests.\",\n      \"state\": \"\
    ENABLED\",\n      \"variants\": {\n        \"on\": 100,\n        \"off\": 0\n\
    \      },\n      \"defaultVariant\": \"off\"\n    },\n    \"imageSlowLoad\": {\n\
    \      \"description\": \"slow loading images in the frontend\",\n      \"state\"\
    : \"ENABLED\",\n      \"variants\": {\n        \"10sec\": 10000,\n        \"5sec\"\
    : 5000,\n        \"off\": 0\n      },\n      \"defaultVariant\": \"off\"\n   \
    \ }\n  }\n}\n"
