apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: 11.5.2
data:
  plugins: grafana-opensearch-datasource
  grafana.ini: '[analytics]

    check_for_updates = true

    [auth]

    disable_login_form = true

    [auth.anonymous]

    enabled = true

    org_name = Main Org.

    org_role = Admin

    [grafana_net]

    url = https://grafana.net

    [log]

    mode = console

    [paths]

    data = /var/lib/grafana/

    logs = /var/log/grafana

    plugins = /var/lib/grafana/plugins

    provisioning = /etc/grafana/provisioning

    [server]

    domain = ''''

    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

    serve_from_sub_path = true

    '
  datasources.yaml: "apiVersion: 1\ndatasources:\n- editable: true\n  isDefault: true\n\
    \  jsonData:\n    exemplarTraceIdDestinations:\n    - datasourceUid: webstore-traces\n\
    \      name: trace_id\n    - name: trace_id\n      url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}\n\
    \      urlDisplayLabel: View in Jaeger UI\n  name: Prometheus\n  type: prometheus\n\
    \  uid: webstore-metrics\n  url: http://prometheus:9090\n- editable: true\n  isDefault:\
    \ false\n  name: Jaeger\n  type: jaeger\n  uid: webstore-traces\n  url: http://jaeger-query:16686/jaeger/ui\n\
    - access: proxy\n  editable: true\n  isDefault: false\n  jsonData:\n    database:\
    \ otel\n    flavor: opensearch\n    logLevelField: severity.text.keyword\n   \
    \ logMessageField: body\n    pplEnabled: true\n    timeField: observedTimestamp\n\
    \    version: 2.18.0\n  name: OpenSearch\n  type: grafana-opensearch-datasource\n\
    \  uid: webstore-logs\n  url: http://opensearch:9200/\n"
  dashboardproviders.yaml: "apiVersion: 1\nproviders:\n- disableDeletion: false\n\
    \  editable: true\n  folder: \"\"\n  name: default\n  options:\n    path: /var/lib/grafana/dashboards/default\n\
    \  orgId: 1\n  type: file\n"
